import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";
import Button from "../components/ui/Button";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { data: user } = api.auth.user.useQuery();
  const logoutMutation = api.auth.logout.useMutation();
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        {user && <h1>Welcome Home, {user.username}</h1>}

        <Button
          className="rounded-lg bg-black p-2 hover:bg-gray-700"
          action={async () => {
            await logoutMutation.mutateAsync();
            await router.push("/auth");
          }}
        >
          sign out
        </Button>
      </main>
    </>
  );
};

export default Home;
